// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKaRhfXcUfpW0CynYBJ5Q2B_fB_RgfwF8',
    appId: '1:456488527414:web:c2e52db00565f8920e9a97',
    messagingSenderId: '456488527414',
    projectId: 'communityapp-16f6c',
    authDomain: 'communityapp-16f6c.firebaseapp.com',
    storageBucket: 'communityapp-16f6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOF-EdnksJfWGadyfMgtTs-oC3TGlhcQg',
    appId: '1:456488527414:android:7b4d1d97872029e90e9a97',
    messagingSenderId: '456488527414',
    projectId: 'communityapp-16f6c',
    storageBucket: 'communityapp-16f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBThSl0iHH0pQ2Z8dda-T16vAhZ4CDRofo',
    appId: '1:456488527414:ios:5f3dcccec6b1a56a0e9a97',
    messagingSenderId: '456488527414',
    projectId: 'communityapp-16f6c',
    storageBucket: 'communityapp-16f6c.appspot.com',
    androidClientId: '456488527414-61a09eb0i7hnhj29i6714i7rju0t4h88.apps.googleusercontent.com',
    iosClientId: '456488527414-3ni3c6mdbpdo1g2hqk75pqppa888j7j0.apps.googleusercontent.com',
    iosBundleId: 'com.akshat.communityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBThSl0iHH0pQ2Z8dda-T16vAhZ4CDRofo',
    appId: '1:456488527414:ios:5f3dcccec6b1a56a0e9a97',
    messagingSenderId: '456488527414',
    projectId: 'communityapp-16f6c',
    storageBucket: 'communityapp-16f6c.appspot.com',
    androidClientId: '456488527414-61a09eb0i7hnhj29i6714i7rju0t4h88.apps.googleusercontent.com',
    iosClientId: '456488527414-3ni3c6mdbpdo1g2hqk75pqppa888j7j0.apps.googleusercontent.com',
    iosBundleId: 'com.akshat.communityApp',
  );
}
